### ISSUE TITLE
Seeking help

### ISSUE THREAD

**Issue by buhuiming** [davidepianca98/KMQTT#20]
Hello, thank you very much for open-sourcing this project. It has been incredibly helpful to me. I have a few questions. I noticed that there are some TODOs in the source code. Will those be completed in the future? Additionally, I couldn't find any callbacks or notifications regarding the connection status in the Client. Do you have any suggestions for how to know the connection status?

**Comment by davidepianca98** [comment]
Hello, yes the idea is to complete the implementation, though currently only a few details are missing, which are not 100% necessary. For example MQTT5 client topic aliases, but the client will work simply by sending the full topics in the PUBLISH messages.
You can check the `connackReceived` attribute to see if the client has connected. Also on disconnection you are going to get an exception in `step()` or `run()`. For now the client doesn't support reconnection so you need to reinstantiate it. I'm open to suggestions on the current API design to make it easier to integrate in various projects, for example adding more callbacks like you asked.
