### ISSUE TITLE
callback for connect / disconnect & manage LWT

### ISSUE THREAD

**Issue by AhmedX6** [davidepianca98/KMQTT#26]
Hello,

The SDK is missing state of connection callback (onConnected / onDisconnected)
Also, I did not find where to manage the LWT message topic from client side.

https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

Could you do these enhancements ?

And possible to keep your up to date version available on Jitpack please ?

Thanks

**Comment by davidepianca98** [comment]
I will add the connection state callbacks when I can, though you can check the value of `connackReceived `in the client object to know if the client is connected.

Regarding the LWT, you can set the various values in the constructor of MQTTClient, specifically `willProperties`, `willTopic`, `willPayload`, `willRetain` and `willQos`.

You can try to get the -SNAPSHOT version on JitPack (https://jitpack.io/#davidepianca98/KMQTT/-SNAPSHOT) but even if it compiles, it won't have the Apple targets. The only way to have them for now is through GitHub packages or by building yourself the library.

**Comment by davidepianca98** [comment]
Added `onConnect` and `onDisconnect` callbacks in https://github.com/davidepianca98/KMQTT/commit/c10f27ee6e1f1435f633e69f96c05af5f1d56a0b. Will be available in the next release.
