### ISSUE TITLE
iOSBuild failed with Could not find 'openssl-its-simulator-arm64'

### ISSUE THREAD

**Issue by wman1980** [davidepianca98/KMQTT#28]
Hi,

I have successfully integrated you MQTT library on my KMM project.

On Android it works and I can subscribe & publish to topics.
On iOS it fails building my iOS application and it does not event start in my simulator.
The build error is:
`> Task :shared:compileKotlinIosSimulatorArm64 FAILED
error: Could not find "openssl-ios-simulator-arm64" in [/Users/MyUser/path/to/project, /Users/MyUser/.konan/klib, /Users/MyUser/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.10/klib/common, /Users/MyUser/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.10/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors`

Do you have any idea what's causing this?

PS: Excluding your mqtt lib and all relevant code from my app fixes building iOS app.

Thanks
Jan

**Comment by davidepianca98** [comment]
Hello, please check the Readme at this link https://github.com/davidepianca98/KMQTT/tree/master#gradle. You have to download the openssl dependency at the specified link, for your platforms and put them in "/Users/MyUser/path/to/project". I have yet to find a solution to bundle the files directly in the maven dependencies. Please let me know if it works.

**Comment by wman1980** [comment]
Thanks, that worked!

Maybe an exclamation mark within the readme would help to make it more obvious.

**Comment by jvondermarck** [comment]
It is so unclear what you said, do we need to paste this folder nativeInterop directly ? or make some changes ? And you did not even talk about if we need to change the text inside the openssl.def...
