### ISSUE TITLE
ssl server certificate not found (IOS only)

### ISSUE THREAD

**Issue by AhmedX6** [davidepianca98/KMQTT#30]
Hello,

Trying to connect on IOS simulator (also a real phone) to mqtt broker with SSL.

My MQTT broker trusts the certificate on device directly, so no need to set any path on Android..

```
if (tlsSettings.serverCertificatePath != null) {
    if (SSL_CTX_load_verify_locations(sslContext, tlsSettings.serverCertificatePath, null) != 1) {
        throw Exception("Server certificate path not found")
    }
} else {
    if (SSL_CTX_load_verify_locations(sslContext, null, getenv(X509_get_default_cert_dir_env()?.toKString())?.toKString()) != 1) {
        throw Exception("Server certificate path not found") //Fail HERE
    }
}
 
```
But in IOS it throws on the "else" branch, any idea ?

Thanks for help.. it's really blocking.

**Comment by davidepianca98** [comment]
Hello, you probably haven't set the server certificate path to authenticate the server and also on iOS there are no default certificates that OpenSSL could find. Try setting the `serverCertificatePath` in the `TLSClientSettings` object as shown here https://github.com/davidepianca98/KMQTT/tree/master#tls-code-example. Obviously use the correct CA certificate for the server you are trying to connect to.

**Comment by AhmedX6** [comment]
Hello,

We tested with two certificates one .pem -> OpenSSL error 1 & one in .crt : "Server certificate path not found".
Both are stored in the cache of the app.

Any idea ?

**Comment by davidepianca98** [comment]
I need to do further testing but I'm quite busy right now. Another thing, are you sure the path to the file given to `TLSClientSettings` is correct? Maybe the file isn't found.

**Comment by AhmedX6** [comment]
The file is found, and is correct but after some investigation I found that Root CA on Linux was not the same as Root CA in Apple. After taking a root ca content of Apple it worked.

**Comment by jvondermarck** [comment]
Can you explain us where did you put the certificate in your path please ? @AhmedX6
