### ISSUE TITLE
Is it possible to add a path in MqttClient?

### ISSUE THREAD

**Issue by RobinChien** [davidepianca98/KMQTT#35]
My MQTT broker URL is ws://broker.emqx.io:8083/mqtt. 
How can I specify the "/mqtt" path in the MQTTClient?

**Comment by davidepianca98** [comment]
Hello, it is not yet possible, I will add the functionality when I have time. Anyway I tried to connect like this and it seems to be working anyway:

```kotlin
val client = MQTTClient(
    MQTTVersion.MQTT5,
    "broker.emqx.io",
    8083,
    null,
    15,
    webSocket = true
) {
    println(it.payload?.toByteArray()?.decodeToString())
}
```

**Comment by davidepianca98** [comment]
Added in https://github.com/davidepianca98/KMQTT/commit/87b20331bd244af4bbe345c6cfc8455bfe48e5e2. Will be available in the next release
