### ISSUE TITLE
Socket connection error on windows native 

### ISSUE THREAD

**Issue by AlessandroColi** [davidepianca98/KMQTT#42]
I am currently implementing a Kotlin multiplatform Project and when I run the Windows 11 native I get a a Socket.IOException: Socket connect failed, error 10047,  that I believe to be the win11 socket error 'Address family not supported by protocol family'.

the error comes up when i try to execute 
```
client.publish(
                     retain = true,
                    Qos.EXACTLY_ONCE,
                    topic,
                    message.toUByteArray(),
                    MQTT5Properties(
                        serverKeepAlive = 5000u,
                        retainAvailable = 1u,))
```                     
where client is:
```
client = MQTTClient(
                    MQTTVersion.MQTT5,
                    host,
                    port,
                    tls = null,
                    userName = username,
                    password = password?.encodeToByteArray()?.toUByteArray(),
                    keepAlive = 5000,
                    cleanStart = false,
                )
```
I run the test locally using mosquitto and the same tests are working fine on JVM and Linux Native

**Comment by davidepianca98** [comment]
Hello, thanks for reporting. It has been fixed in https://github.com/davidepianca98/KMQTT/commit/02683d6fa7b5017628a1a745d075c35cae2d7b8e. I hope to make a new release in a few days.
