### ISSUE TITLE
 "Unable to parse TLS packet header"-error caused by 0-byte-channel-read

### ISSUE THREAD

**Issue by jayc2111** [davidepianca98/KMQTT#5]
#### Description
Function _putOrEnlarge()_ in src/jvmMain/kotlin/socket/tls/TLSSocket.kt:123 does not handle the case when 0 bytes have been received from _super.readToBuffer()_ into the _receiveBuffer_.
Although nothing has been received, we still try to put into the _cacheReceiveBuffer_ - for some reason, this causes a **BufferOverflowException** :-( 
Following that, we will enlarge the buffer and try to unwrap the data which leads to an "Unable to parse TLS packet header" error eventually.

#### Files
 src/jvmMain/kotlin/socket/tls/TLSSocket.kt
 src/jvmMain/kotlin/socket/tcp/Socket.kt

#### To Reproduce
I'm running KMQTT broker using TLS on an android device together with a raspberry pi running mosquitto as client. TLS certificates need to be in place.

Every time I try to publish or subscribe to the broker, i get this "Unable to parse TLS packet header". During debugging, I found out, that i don't get this "0-byte-channel-read" when i set a breakpoint on _tcpEventHandler.read()_ in the do-while-loop in _handleEvent()_ in ServersocketLoop.kt:33. I guess that this "0-byte-channel-read" only happens if the broker sends a message to the client but the client is not fast enough to deliver a complete answer.

**Comment by davidepianca98** [comment]
Hello, thank you for posting the issue. It should be solved in the latest version. Unfortunately I'm having problems with Jitpack so I also uploaded it to GitHub packages but I still have to figure out how it works for downloading the dependency. You can also try to download the jar directly from the releases page if necessary.
Please let me know if that fixed you issue.

**Comment by jayc2111** [comment]
Hey,
wow - thanks a lot for the super fast help :-)
I just tried to re-test with the new jar-file but unfortunately I ran into some conflicts with the kotlin-stdlib and the Java version. I guess that you are using Java 9, right?
I get a Java-related failure when trying to do "receiveBuffer.clear()" - Android Studio seems to be stuck with Java 8 still :-/
So i will wait untill the new version is availble on jitpack :-)

**Comment by davidepianca98** [comment]
Yes I used Java 11 to build the jar. It should now be available on JitPack, today it decided to build correctly, while a few days ago it just timed out 😆. So let me know if that works and fixes the issue.

**Comment by jayc2111** [comment]
Works perfectly now!
Thanks a lot again :-)
