### ISSUE TITLE
Bug in ConnectFlags.connectFlags(byte: Int)

### ISSUE THREAD

**Issue by mice777** [davidepianca98/KMQTT#54]
File: ConnectFlags.kt
Line 32:

val willQos = ((byte shr 4) and 1) or ((byte shl 3) and 1)

`((byte shl 3) and 1)` is always zero!
so you get wrong qos value.

It should be rather:
val willQos = byte.shr(4) and 3

**Comment by davidepianca98** [comment]
Hello, thanks for spotting the issue! Fixed in https://github.com/davidepianca98/KMQTT/commit/09b77d316621c064de07136e85d5ac88b6283f83

**Comment by mice777** [comment]
Credit is for IDEA which spotted this :) 

![image](https://github.com/davidepianca98/KMQTT/assets/3145438/d7c15ccd-b14f-454f-bdd6-df56aa7b8ca1)
