### ISSUE TITLE
KMQTT BROKER - topicAliasMaximum set to 0 even when topicAliasMaximum is set on client.

### ISSUE THREAD

**Issue by nishankhadka09** [davidepianca98/KMQTT#62]
connAck packet -

`MqttConnAck{reasonCode=SUCCESS, sessionPresent=false, restrictions=MqttConnAckRestrictions{receiveMaximum=1024, maximumPacketSize=32768, topicAliasMaximum=0, maximumQos=EXACTLY_ONCE, retainAvailable=true, wildcardSubscriptionAvailable=true, sharedSubscriptionAvailable=true, subscriptionIdentifiersAvailable=true}}`

The topicAliasMaximum is 0 in the connAck message, but the client connection snippet is :

```
(mqttClient as Mqtt5Client?)?.toAsync()?.connectWith()?.restrictions()
            ?.topicAliasMaximum(65535)?.applyRestrictions()?.cleanStart(true)?.send()

```

Shouldn't the connAck have topicAliasMaximum of  not 0??

Client disconnects once I publish to two or more topics  saying -  Exception while decoding PUBLISH: topic alias must not be 0

**Comment by davidepianca98** [comment]
Hey thanks for the bug report, I'll look into it as soon as I have time
