### ISSUE TITLE
proposal: Pass CoroutineExceptionHandler

### ISSUE THREAD

**Issue by hkusu** [davidepianca98/KMQTT#65]
Currently, it is not possible to catch exceptions during `.runSuspend`.

https://github.com/davidepianca98/KMQTT/blob/fcef2ca6d84550235f3e62ad5074af419d6238f2/kmqtt-client/src/commonMain/kotlin/MQTTClient.kt#L429-L433

My suggestion is to be able to pass `CoroutineExceptionHandler`.

**Comment by davidepianca98** [comment]
Hello, thanks for the suggestion. Would you be able to open a pull request with the change? Otherwise I'll make it as soon as I can but it might take a while.

**Comment by davidepianca98** [comment]
Implemented here https://github.com/davidepianca98/KMQTT/commit/9fa3d003d2b0d1f74f448966e211684aee2a5789
