### ISSUE TITLE
Kotlin native could not find "openssl"

### ISSUE THREAD

**Issue by ssuukk** [davidepianca98/KMQTT#68]
This might be the same as #14, but since it is marked closed, I'm posting as a new issue. I'm experiencing this with Kotlin Multiplatform, on Linux build:

Task :shared:compileKotlinLinuxX64 FAILED
e: KLIB resolver: Could not find "openssl" in [/home/qus/StudioProjects/dms-agent/linuxX64App, /home/qus/.konan/klib, /home/qus/.konan/kotlin-native-prebuilt-linux-x86_64-2.0.0/klib/common, /home/qus/.konan/kotlin-native-prebuilt-linux-x86_64-2.0.0/klib/platform/linux_x64]

KLIB resolver: Could not find "openssl" in [/home/qus/StudioProjects/dms-agent/linuxX64App, /home/qus/.konan/klib, /home/qus/.konan/kotlin-native-prebuilt-linux-x86_64-2.0.0/klib/common, /home/qus/.konan/kotlin-native-prebuilt-linux-x86_64-2.0.0/klib/platform/linux_x64]

Is there anything I can do? The prebuilt binary doesn't seem to be there anymore...

**Comment by davidepianca98** [comment]
Please check this info in the readme: https://github.com/davidepianca98/KMQTT?tab=readme-ov-file#gradle. Unfortunately there is no openssl Kotlin multiplatform library yet, so this is the best we can do for now.

**Comment by ssuukk** [comment]
Do I have to rename it somehow? I have tried it in the main directory and inside linuxX64app, but it still couldn't find it...
